### PR TITLE
[JBEE-246] Jakarta EE BOMs

### PR DESCRIPTION
**Pull request by emmartins**
Issue: https://issues.jboss.org/browse/JBEE-246

### CODE REVIEW

**Comment by emmartins** [comment]
maven dependency:tree output:
```
org.jboss.spec:jboss-jakartaee-all-8.0:jar:1.0.0.Final-SNAPSHOT
[INFO] +- com.sun.activation:jakarta.activation:jar:1.2.1:compile
[INFO] +- jakarta.enterprise:jakarta.enterprise.cdi-api:jar:2.0.2:compile
[INFO] +- jakarta.inject:jakarta.inject-api:jar:1.0:compile
[INFO] +- jakarta.json:jakarta.json-api:jar:1.1.6:compile
[INFO] +- jakarta.json.bind:jakarta.json.bind-api:jar:1.0.2:compile
[INFO] +- javax.jws:jsr181-api:jar:1.0-MR1:compile
[INFO] +- com.sun.mail:jakarta.mail:jar:1.6.4:compile
[INFO] +- jakarta.persistence:jakarta.persistence-api:jar:2.2.3:compile
[INFO] +- jakarta.security.enterprise:jakarta.security.enterprise-api:jar:1.0.2:compile
[INFO] +- jakarta.validation:jakarta.validation-api:jar:2.0.2:compile
[INFO] +- org.jboss.spec.javax.annotation:jboss-annotations-api_1.3_spec:jar:2.0.1.Final:compile
[INFO] +- org.jboss.spec.javax.batch:jboss-batch-api_1.0_spec:jar:2.0.0.Final:compile
[INFO] +- org.jboss.spec.javax.ejb:jboss-ejb-api_3.2_spec:jar:2.0.0.Final:compile
[INFO] +- org.jboss.spec.javax.el:jboss-el-api_3.0_spec:jar:2.0.0.Final:compile
[INFO] +- org.jboss.spec.javax.enterprise.concurrent:jboss-concurrency-api_1.0_spec:jar:2.0.0.Final:compile
[INFO] +- org.jboss.spec.javax.faces:jboss-jsf-api_2.3_spec:jar:3.0.0.Final:compile
[INFO] +- org.jboss.spec.javax.interceptor:jboss-interceptors-api_1.2_spec:jar:2.0.0.Final:compile
[INFO] +- org.jboss.spec.javax.management.j2ee:jboss-j2eemgmt-api_1.1_spec:jar:2.0.0.Final:compile
[INFO] +- org.jboss.spec.javax.resource:jboss-connector-api_1.7_spec:jar:2.0.0.Final:compile
[INFO] +- org.jboss.spec.javax.security.jacc:jboss-jacc-api_1.5_spec:jar:2.0.0.Final:compile
[INFO] +- org.jboss.spec.javax.security.auth.message:jboss-jaspi-api_1.1_spec:jar:2.0.1.Final:compile
[INFO] +- org.jboss.spec.javax.jms:jboss-jms-api_2.0_spec:jar:2.0.0.Final:compile
[INFO] +- org.jboss.spec.javax.servlet:jboss-servlet-api_4.0_spec:jar:2.0.0.Final:compile
[INFO] +- org.jboss.spec.javax.servlet.jsp:jboss-jsp-api_2.3_spec:jar:2.0.0.Final:compile
[INFO] +- org.apache.taglibs:taglibs-standard-spec:jar:1.2.6-RC1:compile
[INFO] +- org.apache.taglibs:taglibs-standard-impl:jar:1.2.6-RC1:compile
[INFO] +- org.jboss.spec.javax.transaction:jboss-transaction-api_1.3_spec:jar:2.0.0.Final:compile
[INFO] +- org.jboss.spec.javax.ws.rs:jboss-jaxrs-api_2.1_spec:jar:2.0.0.Final:compile
[INFO] +- org.jboss.spec.javax.websocket:jboss-websocket-api_1.1_spec:jar:2.0.0.Final:compile
[INFO] +- org.jboss.spec.javax.xml.bind:jboss-jaxb-api_2.3_spec:jar:2.0.0.Final:compile
[INFO] +- org.jboss.spec.javax.xml.soap:jboss-saaj-api_1.4_spec:jar:1.0.0.Final:compile
[INFO] \- org.jboss.spec.javax.xml.ws:jboss-jaxws-api_2.3_spec:jar:2.0.0.Final:compile
```

**Comment by emmartins** [comment]
@scottmarlow please have a look at this

**Comment by scottmarlow** [comment]
Created [eclipse-ee4j/jws-api/issues/48](https://github.com/eclipse-ee4j/jws-api/issues/48)
Also created [eclipse-ee4j/jax-ws-api/issues/89](https://github.com/eclipse-ee4j/jax-ws-api/issues/89)

**Comment by scottmarlow** [comment]
@emmartins which line in the dependency are you concerned with?  

Is it "org.jboss.spec.javax.xml.ws:jboss-jaxws-api_2.3_spec:jar:2.0.0.Final:compile"?

The responses that I got back from the above issues, is:
```
https://github.com/eclipse-ee4j/jax-ws-api/issues/89: there's no 2.3.3 right now. It must go through ballot first.

https://github.com/eclipse-ee4j/jws-api/issues/48: there's no 2.1.0 right now. It must go through ballot first.
```

**Comment by emmartins** [comment]
I will just exclude transitives here, but sounds like our jaxws fork should
then go back to 2.3.2?

**Comment by jamezp** [comment]
Are these meant to be used by end users?

**Comment by scottmarlow** [comment]
@emmartins good question, our fork is passing all Jakarta EE platform TCK tests, which means that our fork is Jakarta EE 8 compliant, but the upstream fork 2.3.3 has not been voted on yet.  

Upstream [commit 9938eceecfcdb9a2fb33e97780bf148790aefc81](https://github.com/jboss/jboss-jakarta-jax-ws-api_spec/commit/9938eceecfcdb9a2fb33e97780bf148790aefc81) is the most recent change that we included.  Going back to upstream 2.3.2 until 2.3.3 is approved, seems safer than including the 2.3.3 commits before approved.

@jamezp yes, JAX-WS can be used by applications.

**Comment by scottmarlow** [comment]
[2.3.2](https://github.com/eclipse-ee4j/jax-ws-api/commits/2.3.2-RELEASE) is from last December.

**Comment by jamezp** [comment]
If that's the case do we want to be changing the artifact id? I was under the impression that we don't want to do that.

**Comment by scottmarlow** [comment]
To check this pr, we need to verify that the mentioned above bom dependency tree matches GAV used in [WF 18 final](https://github.com/wildfly/wildfly/blob/18.0.0.Final/pom.xml#L239) + [WF core 10.0.0.Final](https://github.com/wildfly/wildfly-core/blob/10.0.0.Final/pom.xml#L143)

For example, com.sun.activation:jakarta.activation:jar:1.2.1 matches

**Comment by scottmarlow** [comment]
javax.jws:jsr181-api:jar:1.0-MR1 is correct for WF18 but could change in near future to different GA based on jakarta.jws:jakarta.jws-api

All of the dependencies match WF18

**Review by scottmarlow — APPROVED** [review]

**Pull request merged**
